workflows:
  dylib-inject:
    name: Build Dylib & Inject into IPA
    max_build_duration: 60
    environment:
      vars:
        TARGET_BUNDLE_ID: "com.woostergames.animalcompany"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install Theos
        script: |
          set -e
          export THEOS=$HOME/theos

          if [ ! -d "$THEOS" ]; then
            git clone --recursive https://github.com/theos/theos.git $THEOS
          fi

          SDK_DIR=$THEOS/sdks
          mkdir -p $SDK_DIR

          XCODE_SDK=$(xcrun --sdk iphoneos --show-sdk-path 2>/dev/null)
          SDK_NAME=$(basename "$XCODE_SDK")
          echo "[*] Found Xcode SDK: $SDK_NAME at $XCODE_SDK"

          if [ ! -e "$SDK_DIR/$SDK_NAME" ]; then
            ln -sf "$XCODE_SDK" "$SDK_DIR/$SDK_NAME"
          fi

          SDK_VERSION=$(echo "$SDK_NAME" | sed 's/iPhoneOS//;s/\.sdk//')
          echo "[✓] SDK version: $SDK_VERSION"

          echo "THEOS=$HOME/theos" >> $CM_ENV
          echo "SDKVERSION=$SDK_VERSION" >> $CM_ENV
          ls $SDK_DIR

      - name: Install inject_dylib
        script: |
          set -e
          brew install ldid 2>/dev/null || true

          if ! command -v insert_dylib &>/dev/null; then
            git clone https://github.com/tyilo/insert_dylib.git /tmp/insert_dylib
            cd /tmp/insert_dylib
            xcodebuild -configuration Release SYMROOT=/tmp/insert_dylib/build 2>/dev/null
            BUILT=$(find /tmp/insert_dylib/build -name "insert_dylib" -type f | head -1)
            cp "$BUILT" /usr/local/bin/insert_dylib
            chmod +x /usr/local/bin/insert_dylib
            echo "[✓] insert_dylib installed"
          fi

      - name: Build Dylib
        script: |
          set -e
          export THEOS=$HOME/theos
          export THEOS_MAKE_PATH=$THEOS/makefiles
          cd $CM_BUILD_DIR
          make -j$(sysctl -n hw.ncpu) SDKVERSION=$SDKVERSION 2>&1
          echo "[*] Built artifacts:"
          find . -name "*.dylib" | head -10

      - name: Download IPA
        script: |
          set -e
          FILE_ID="10zfkTLaXudtJZJi-wdGO4Y5Si1Aw6lI4"
          OUTPUT="target.ipa"
          echo "[*] Downloading IPA from Google Drive..."
          pip3 install gdown --quiet
          gdown "https://drive.google.com/uc?id=${FILE_ID}" -O "$OUTPUT"
          echo "[✓] Downloaded: $(du -sh $OUTPUT | cut -f1)"

      - name: Inject Dylib into IPA
        script: |
          set -e
          cd $CM_BUILD_DIR
          DYLIB_PATH=$(find . -name "MyTweak.dylib" | head -1)
          echo "[*] Found dylib: $DYLIB_PATH"

          IPA_PATH=$(find . -name "*.ipa" | grep -v patched | head -1)
          if [ -z "$IPA_PATH" ]; then
            echo "[!] No IPA found."
            exit 1
          fi
          echo "[*] Target IPA: $IPA_PATH"

          chmod +x inject.sh
          bash inject.sh "$IPA_PATH" "$DYLIB_PATH"

      - name: Re-sign IPA (ad-hoc)
        script: |
          set -e
          cd $CM_BUILD_DIR
          PATCHED_IPA=$(find . -name "patched_*.ipa" | head -1)
          WORK_DIR=$(mktemp -d)
          unzip -q "$PATCHED_IPA" -d "$WORK_DIR"
          APP_PATH=$(find "$WORK_DIR/Payload" -name "*.app" | head -1)

          # Write a minimal real entitlements file instead of using /dev/null
          ENTITLEMENTS=$(mktemp /tmp/entitlements.XXXXXX.plist)
          cat > "$ENTITLEMENTS" << 'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>application-identifier</key>
            <string>*</string>
            <key>get-task-allow</key>
            <true/>
          </dict>
          </plist>
          PLIST

          # Sign all dylibs and frameworks first
          find "$APP_PATH" \( -name "*.dylib" -o -name "*.framework" \) | while read f; do
            codesign --force --sign - "$f" 2>/dev/null || true
          done

          # Sign the app bundle
          codesign --force --sign - --entitlements "$ENTITLEMENTS" "$APP_PATH"

          rm -f "$ENTITLEMENTS"

          IPA_NAME=$(basename "$PATCHED_IPA")
          cd "$WORK_DIR"
          zip -qr "${OLDPWD}/signed_${IPA_NAME}" Payload
          cd "$OLDPWD"
          rm -rf "$WORK_DIR"
          echo "[✓] Re-signed IPA: signed_${IPA_NAME}"

    artifacts:
      - "**/*.dylib"
      - "**/patched_*.ipa"
      - "**/signed_*.ipa"
