workflows:
  dylib-inject:
    name: Build Dylib & Inject into IPA
    max_build_duration: 60
    environment:
      vars:
        TARGET_BUNDLE_ID: "com.example.targetapp"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install Theos
        script: |
          set -e
          if [ ! -d "$THEOS" ]; then
            export THEOS=~/theos
            bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          fi
          echo "THEOS=$HOME/theos" >> $CM_ENV

      - name: Install inject_dylib & optool
        script: |
          set -e
          brew install ldid 2>/dev/null || true

          if ! command -v insert_dylib &>/dev/null; then
            git clone https://github.com/tyilo/insert_dylib.git /tmp/insert_dylib
            cd /tmp/insert_dylib
            xcodebuild -configuration Release -arch x86_64 -arch arm64 SYMROOT=/tmp/insert_dylib/build
            cp /tmp/insert_dylib/build/Release/insert_dylib /usr/local/bin/
          fi

      - name: Build Dylib
        script: |
          set -e
          export THEOS=$HOME/theos
          export THEOS_MAKE_PATH=$THEOS/makefiles
          cd $CM_BUILD_DIR
          make -j$(sysctl -n hw.ncpu) 2>&1 || make 2>&1
          echo "[*] Built artifacts:"
          find . -name "*.dylib" | head -10

      - name: Inject Dylib into IPA
        script: |
          set -e
          cd $CM_BUILD_DIR
          DYLIB_PATH=$(find . -name "MyTweak.dylib" | head -1)
          echo "[*] Found dylib: $DYLIB_PATH"
          IPA_PATH=$(find . -name "*.ipa" | grep -v patched | head -1)
          if [ -z "$IPA_PATH" ]; then
              echo "[!] No IPA found. Upload an IPA to your repo root or uncomment the download step."
              exit 1
          fi
          echo "[*] Target IPA: $IPA_PATH"
          chmod +x inject.sh
          bash inject.sh "$IPA_PATH" "$DYLIB_PATH"

      - name: Re-sign IPA (ad-hoc)
        script: |
          set -e
          cd $CM_BUILD_DIR
          PATCHED_IPA=$(find . -name "patched_*.ipa" | head -1)
          WORK_DIR=$(mktemp -d)
          unzip -q "$PATCHED_IPA" -d "$WORK_DIR"
          APP_PATH=$(find "$WORK_DIR/Payload" -name "*.app" | head -1)
          find "$APP_PATH" \( -name "*.dylib" -o -name "*.framework" \) -exec codesign --force --sign - {} \;
          codesign --force --sign - --entitlements /dev/null "$APP_PATH"
          IPA_NAME=$(basename "$PATCHED_IPA")
          cd "$WORK_DIR"
          zip -qr "${OLDPWD}/signed_${IPA_NAME}" Payload
          cd "$OLDPWD"
          rm -rf "$WORK_DIR"
          echo "[✓] Re-signed IPA: signed_${IPA_NAME}"

    artifacts:
      - "**/*.dylib"
      - "**/patched_*.ipa"
      - "**/signed_*.ipa"
